### ISSUE TITLE
Ball Launcher

### ISSUE THREAD

**Issue by amcaleer271** [uf-mil-mechanical/tasks#1]
NaviGator needs a ball launcher to fire racquetballs at a small target 10-15 ft away. It must be accurate and have a predictable trajectory. A key consideration is keeping all components and balls dry to maintain physical launching conditions.

**Comment by amcaleer271** [comment]
Created mock design of the ball launcher and ordered parts. Now working to make the design manufacturable and assembleable. Plan to have design finished this week (by 9/6) and mechanism built in lab within two week (9/20).

![image](https://github.com/user-attachments/assets/24f5f69c-b851-44d6-9c9d-08f0afb7e54e)

**Comment by amcaleer271** [comment]
Finalizing design (shown below) for the ball launcher. Electronic parts have arrived and electrical has begun working on the necessary components. ![Image](https://github.com/user-attachments/assets/492fceb0-45da-4746-800e-49dada46ab2c)

**Comment by adamhamdan8** [comment]
Bought the polycarb, bringing it in later tonight, its in my car right now!

**Comment by amcaleer271** [comment]
Printed prototype parts, made appt to cut waterjet parts on 9/26

**Comment by amcaleer271** [comment]
Mechanical assembly of ball launcher complete! Waiting for electrical to finish their board so we can test, then mount on NaviGator!![Image](https://github.com/user-attachments/assets/2b31b311-34d2-465f-b7e1-5dd2b61a373d)

**Comment by amcaleer271** [comment]
After testing the ball launcher in lab, there are a few things than need to be tweaked before it can be installed on the boat.

- The whole mechanism vibrates quite a lot. This is likely from the motor not being fully secured to the housing, and the flywheel being supported from only one side. Furthermore, some parts need to be better secured, including all acrylic. 
- The mechanism for ensuring only one ball enters the flywheel also needs to be tweaked, the arms need to be longer. 

Things to fix:

- Support flywheel from both sides
- Add support for the back end of the motor
- Make the nuts on the motor more accessible so they can be tightened with a wrench
- Thicken the walls of the housing so they acrylic pieces can be secured
- Switch nuts to nyloc nuts so they don't undo with vibrations
- Fix ball guide mechanism so it functions as intended
- Make it easier to install the flywheel.

**Comment by adamhamdan8** [comment]
@amcaleer271 As the flywheel rotates it seems that the thread is screwing and unscrewing. That does not seem intentional is this before or after the most recent fix?

**Comment by amcaleer271** [comment]
After testing the ball launcher on NaviGator at Lake Wauburg today, this issue is closed! The ball launcher is reasonably accurate, hitting either the large or small target from a distance of ~20ft at a rate of ~60%. At this range the trajectory of the ball varies by about 2ft laterally and vertically. We are going to try angling the launcher downwards slightly to reduce the arc, but other than that the issue is complete! A full repo of the parts is available at https://github.com/amcaleer271/MIL_Ball_Launcher
