### ISSUE TITLE
[Props and Obstacles] Scan the Code

### ISSUE THREAD

**Issue by lorantdomokos** [uf-mil-mechanical/tasks#11]
NaviGator needs to approach a light tower out in the lake that houses an LED array capable of flashing different colors. It needs to float above the water with a pole that houses the lighting. Specifications are in the handbook, but an image is included below.

Deliverables include:
- A BOM for all the parts and where to buy them from
- Constructing the light tower
- Communicating with electrical and software teams

![Screen Shot 2024-09-09 at 3 30 49 PM](https://github.com/user-attachments/assets/bb7520a3-3734-4bbf-b5a2-6980f2338b59)

**Comment by RyanHoburg** [comment]
The dock blocks recommended by the handbook are extremely expensive. I called and got quotes from 2 different companies and searched for used ones online and the pricing just isn't feasible. After speaking with Dr. Schwartz a pvc pool noodle design is the best way to go.

**Comment by RyanHoburg** [comment]
BOM:

- 8 90 degree connectors
- 4 T-shaped connectors
- 4 4-way connectors
-  A connector with holes of 5 sides (if they don't have this then just get 2 more 4-way connectors and I'll figure it out)
- About 72 feet of pvc pipe
- About 60 feet of pool noodles
- 5-15 straight connectors (So you don't have to stress about the length of pvc you're buying as much and if they dont match we can add and subtract. If you get all the perfect lengths then we won't need these but I'm assuming cutting will have to be done)
- PVC glue if we don't have any already
- Bungee cords (I would like to use these in order to prop up the pole supporting the light in the middle and to secure the whole base together. This is something that might be bought in a second trip because the length and tension are gonna be something we want to check before buying)
- A lot of zip ties

**Comment by RyanHoburg** [comment]
Also I need to talk with electrical to figure out exactly how they want the lights to be mounted and what the housing is going to end up looking like. The above list is for the base and a pole going up, it does not include the housing for the light.

**Comment by RyanHoburg** [comment]
I would also like to tie some kind of weight (depending on how well this floats) to the bottom of the float on a length of 2-3 foot line to ensure it has no desire to flip.

**Comment by adamhamdan8** [comment]
> BOM:
> 
> * 8 90 degree connectors
> * 4 T-shaped connectors
> * 4 4-way connectors
> * A connector with holes of 5 sides (if they don't have this then just get 2 more 4-way connectors and I'll figure it out)
> * About 72 feet of pvc pipe
> * About 60 feet of pool noodles
> * 5-15 straight connectors (So you don't have to stress about the length of pvc you're buying as much and if they dont match we can add and subtract. If you get all the perfect lengths then we won't need these but I'm assuming cutting will have to be done)
> * PVC glue if we don't have any already
> * Bungee cords (I would like to use these in order to prop up the pole supporting the light in the middle and to secure the whole base together. This is something that might be bought in a second trip because the length and tension are gonna be something we want to check before buying)
> * A lot of zip ties

Could you put this in an excel file or something like that

**Comment by cbrxyz** [comment]
@RyanHoburg Thank you for your diligence and speed in finishing this :) (from the software team lol)

**Comment by adamhamdan8** [comment]
> I would also like to tie some kind of weight (depending on how well this floats) to the bottom of the float on a length of 2-3 foot line to ensure it has no desire to flip.

We have weights and pool noodles in the MAE-B storage room. Let me know when you have time and I can take you in there to grab some pool noodles as well as weights. If you need more let me know and I will purchase more pool noodles. Whenever you can come in to build that would be great! Thanks again @RyanHoburg

**Comment by adamhamdan8** [comment]
@RyanHoburg PVC, corrugated plastic (if you need any), glue, and zipties are in the lab as of last night. Pool noodles, weights, and other miscellaneous things are in the MAEB storage room. Let me know if you need to buy anything else, but the due date on this was just shifted to next weekend, around 9/21. Thanks

**Comment by RyanHoburg** [comment]
![image](https://github.com/user-attachments/assets/1f8d4e24-648e-4ee5-91c1-3cbdce8a9c0d)

**Comment by RyanHoburg** [comment]
![image](https://github.com/user-attachments/assets/9183cd4f-d181-4241-af6d-b043e1a4ad87)
The pole for the light tower turned out better than i thought and I am going to use pvc glue to secure it along with 4 bungee cords

**Comment by adamhamdan8** [comment]
> ![image](https://private-user-images.githubusercontent.com/180553860/368293790-9183cd4f-d181-4241-af6d-b043e1a4ad87.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODE1NzYsIm5iZiI6MTcyNjY4MTI3NiwicGF0aCI6Ii8xODA1NTM4NjAvMzY4MjkzNzkwLTkxODNjZDRmLWQxODEtNDI0MS1hZjZkLWIwNDNlMWE0YWQ4Ny5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTc0MTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI2M2I5YjZhNDQ3NWYwOGZhMzNkYzJkNDczY2Y0ZGMxNTI3YTAyMzFlNmI0NDc4NTU3NWE1ZThmYzMyZThmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ELMQVNKDUOZEikuAPlW-GusoHct2Ek9S0rL3IUgScZQ) The pole for the light tower turned out better than i thought and I am going to use pvc glue to secure it along with 4 bungee cords

Thats great! The project has gotten a little larger in scope so I think I'll have you figure out the structural and support mechanisms while I figure out the tube and mounting situation!

**Comment by adamhamdan8** [comment]
Please use the google form in #mechanicalinfo in discord to put in the stuff you want me to buy!

**Comment by RyanHoburg** [comment]
Models uploaded to print queue in order to mount LED panels. Also cut holes in existing LED mount in order to mount the extension and brackets for mounting.

**Comment by adamhamdan8** [comment]
Electrical kept breaking the panels so this keeps getting pushed back, but once we find cheap pool noodles and print the mounts we should be good. @RyanHoburg Do you want to design the mount for the battery tube at the bottom of the light tower as well?

**Comment by adamhamdan8** [comment]
@RyanHoburg spoke with @lorantdomokos and adrian about the battery situation, it seems there is no need to use a tube. The box and everything will be 3D printed soon

**Comment by RyanHoburg** [comment]
The LED panels are ready to be mounted in the box whenever electrical can do it. I need to make 1 different bracket to mount it to the pole properly. The battery will just be sealed in a box.

**Comment by adamhamdan8** [comment]
> The LED panels are ready to be mounted in the box whenever electrical can do it. I need to make 1 different bracket to mount it to the pole properly. The battery will just be sealed in a box.

We will need to take the battery out and charge it/swap it out throughout the day. Make sure to make that as easy as possible for us to do.

**Comment by adamhamdan8** [comment]
@RyanHoburg Just want to check on everything here, we need to make sure that this is ready for this Sunday. I know that we need to work with Adrian but we need the tower to be assembled at testing!

**Comment by RyanHoburg** [comment]
I was hoping to put it all together later today but I've been talking with Adrian and they still haven't had a chance to do the electrical stuff. All the mounts are printed and the battery box is done.

**Comment by RyanHoburg** [comment]
All that's left is to attach more pool noodles which will probably be done best at the water. Light tower mounted and electronics work. The center square is pvc glued together to make it more stable. To transport it the actual pole comes out of the center as soon as the bungees are detached.

**Comment by adamhamdan8** [comment]
@RyanHoburg One of the brackets has disappeared, I think the one different one. Could you print another and have it assembled in Cimar to make sure that we can disassemble it and bring it to the Lake this weekend? Also ziptie the pool noodles

**Comment by RyanHoburg** [comment]
![image](https://github.com/user-attachments/assets/20d18d75-665a-436f-a12c-24f074077d94)

Put it back together

**Comment by adamhamdan8** [comment]
Great thanks for the hard work! Hopefully they were able to utilize it well in testing
