### ISSUE TITLE
Hydrophone Mounting System

### ISSUE THREAD

**Issue by lorantdomokos** [uf-mil-mechanical/tasks#12]
Associated Task: Entrance and Exit Gate

In between the gates will be a submerged beacon. We have to use the hydrophones to identify which gate to go through. We currently have a hydrophone system on the NavTube of the submarines that can use a long ethernet cable to connect to the main computer. We need to submerge the hydrophones, mount the NavTube and connect it up to the main computer and make sure water can't get in the NavTube.

**Comment by MarcinPlaza** [comment]
![Image](https://github.com/user-attachments/assets/957c1666-943e-4299-aab0-77351c3faa45)

Created cross beam mount for hydrophone, plan is to insert a piece of aluminum angle as the arm, still need to design the hydrophone mount itself.

**Comment by MarcinPlaza** [comment]
![Image](https://github.com/user-attachments/assets/d3e92b16-9f05-43c2-aeef-91d6d8ea7ec7)
Created Hydrophone mount for the other end of the aluminum angle arm.

**Comment by Harin-0253** [comment]
<img width="380" alt="Screenshot 2024-09-15 223235" src="https://github.com/user-attachments/assets/b070bba1-db5d-4f40-9d30-0f32e368da28">

Modified the nav tube bracket to be used on an 8020 arm.

**Comment by MarcinPlaza** [comment]
![IMG_6263](https://github.com/user-attachments/assets/af83c182-a8d6-4334-82a6-88bfbe74b7df)
![IMG_6259](https://github.com/user-attachments/assets/78623670-b469-4712-a1e8-0a5160b45460)
Test printed the mount and cut the aluminum, and it looks like it all fits great. Ill make one wall a little thicker and print it in petg for a final part.

**Comment by Harin-0253** [comment]
<img width="514" alt="Screenshot 2024-09-22 231310" src="https://github.com/user-attachments/assets/1c11f7b5-1873-43e7-b3f8-94540a6bece5">

Made a sled for the hydrophone tube, and also have a final design for the tube mount, I just need the hydrophone mount cad from marcin to merge the designs.

**Comment by MarcinPlaza** [comment]
Hey @Harin-0253 not really sure where I should put the files since I don't see a navigator project so I put all the files and assembly in sub9>Hydrophone>navigator hydrophone in the Fusion. let me know if you need anything else.

**Comment by MarcinPlaza** [comment]
Unfortunately couldn't finish the hydrophone mount this week. I removed what was left of the prototype arm but I couldn't print the final strengthened PETG before UF closed down.

**Comment by Harin-0253** [comment]
<img width="134" alt="Screenshot 2024-09-29 235036" src="https://github.com/user-attachments/assets/33a08121-ba30-4792-b786-7e895665d4a6">

Was not able to get any printing done before the hurricane, but I made a rod to mount the hydrophone tube onto, that goes over the aluminum extrusion.

**Comment by adamhamdan8** [comment]
Just wanted to add that we are trying to move the hydrophones away from the thrusters! That may be a little difficult but likely a new mounting mechanism will need to be designed, at least as a backup. Theres a chance moving the hydrophones into the middle is fine.

**Comment by Harin-0253** [comment]
![IMG_8200](https://github.com/user-attachments/assets/1555c919-fe16-4135-80d1-2c4feb534729)


![IMG_8199](https://github.com/user-attachments/assets/1fc39764-6e5d-466b-bff7-5304b8ed88a4)


Printed the nav tube mounts and made sure they worked and assembled properly.

**Comment by MarcinPlaza** [comment]
![IMG_6364](https://github.com/user-attachments/assets/d1c547e1-a8fd-4258-8905-ed17d8ffbf6d)
Finishd hydrophone mount, though nav tube holes will need to be moved as the cables are too short.

**Comment by adamhamdan8** [comment]
I was informed the part that holds the middle beam has broken. Please make time to go to CIMAR and look at it, make necessary adjustments, and get another mount printed that hopefully won't break with the hydrophones on them!!

**Comment by adamhamdan8** [comment]
Just to document on here what is going on, we have decided to go with a hinged design so that the hydrophones do not drag on the floor as we are pushing the boat into the water or are taking it out. @MarcinPlaza and @Harin-0253 are working on implementing that now so that we can test the hydrophones this weekend!

**Comment by MarcinPlaza** [comment]
Just finished actually. Remade the arm and bolted the hinge directly to the crossbeam. 
![IMG_7697](https://github.com/user-attachments/assets/6257c83d-6165-4fe7-af4c-d63c9650fb3e)

**Comment by Harin-0253** [comment]
Printed the final mount and attached it to the arm.

**Comment by adamhamdan8** [comment]
@MarcinPlaza and @Harin-0253 Does the mounting arm stay up? We kinda want it to be able to be held up or held down. This really only holds it in one position and then we have to manually hold it up. See if you can jerry-rig something or do something quick. Right now it is out on lake wauburg

**Comment by MarcinPlaza** [comment]
Sorry I didn’t post an update. I did that yesterday, there is a rotating locking bracket that locks it in the up position. When the bracket is rotated to be parallel with the arm it becomes free and the elastic holds it in the down position.

**Comment by cbrxyz** [comment]
There is a green screwdriver in the lab that has a 5/32 allen key bit, which we used to screw in/unscrew the hydrophones today. We brought it back with us since it was the only 5/32 bit we could seem to find at the lake, just so you know! We'll need to bring the same screwdriver (or an equivalent) on Sunday! I'm going to leave it by Zobelisk (forward to: #leads)
