### ISSUE TITLE
Antenna Securing Method

### ISSUE THREAD

**Issue by amcaleer271** [uf-mil-mechanical/tasks#19]
The main antenna for NaviGator (large cylinder on top near the front, which looks like a piece of PVC) needs to be secured during transport and held upright during deployment. 

The antenna should be held down securely during transport, but able to be deployed reasonably quickly, ideally without tools. During testing, the antenna should securely be held upright.

**Comment by space-cat-explorer** [comment]
Didn't get a great start on this, and won't be able to focus on it a ton this week because of exams and the career fair. I went to cimar and took pictures of the antenna to try and brainstorm.

**Comment by space-cat-explorer** [comment]
I went to testing last week but couldn't go this week due to a big exam week coming up. I have some ideas for what I am going to do for this design, I just need to go to cimar and look at what holes are available to secure brackets onto.

**Comment by space-cat-explorer** [comment]
![image](https://github.com/user-attachments/assets/834dda4e-22e8-4fea-bcb5-55a55c88c40f

**Comment by space-cat-explorer** [comment]
![image](https://github.com/user-attachments/assets/70fe7b06-9fe7-46e2-8dee-72b328fef3ab)

**Comment by space-cat-explorer** [comment]
Thinking about using a collapsible 90 degree bracket for securing the antenna, just need to go to CIMAR to look at where it could be secured so that I can add one to the order form and possibly 3D print any necessary mounts for it.

**Comment by adamhamdan8** [comment]
> Thinking about using a collapsible 90 degree bracket for securing the antenna, just need to go to CIMAR to look at where it could be secured so that I can add one to the order form and possibly 3D print any necessary mounts for it.

Hey Sophie keep in mind we only have until the end of next week before the competition!

**Comment by space-cat-explorer** [comment]
Dr. Schwartz said we should just take off the antenna for transport, so I figured this wasn't something that needed to get done before competition, especially since the existing mount works really well for keeping it upright. Let me know if you guys still think it is necessary to have a system to secure it when in the down position.

**Comment by adamhamdan8** [comment]
Fine by me, we can just close the task. Thanks Sophie!
