### ISSUE TITLE
Drone Landing Pad

### ISSUE THREAD

**Issue by adamhamdan8** [uf-mil-mechanical/tasks#2]
NaviGator is to have an autonomous drone that is going to take off and land from a pad on the boat. The current landing pad needs to be reviewed and likely reinforced. Additionally, to allow for the drone to land and remain stable, we need to add a specialized qr code as well as grip tape to the top of the pad. The general process is as follows:

- Evaluate the current landing pad (in CIMAR)
- Decide if reinforcement needs to be made, and then designing, machining, and implementing them if necessary
- Communicating with Software to generate the specialized qr code and adhere it to the landing pad
- Adding skate grip tape to increase friction

**Comment by nonagaga** [comment]
![image](https://github.com/user-attachments/assets/7956c75f-861a-4cb5-95a1-3c16a1dd0151)![image](https://github.com/user-attachments/assets/b68c9fc7-56cf-4f04-a774-7422eddaa83c)

Old landing pad has been moved to the new lab. Conceptualizing designs with @bcobo04

**Comment by bcobo04** [comment]
Talked with @nonagaga about the possibility of using the magnet to secure the drone to the pad which will reduce likelihood that drone will fall off and maybe even be a system for snapping the drone into place during the landing process.

**Comment by adamhamdan8** [comment]
@bcobo04 and @nonagaga we are probably going to use a telescopic arm for the mechanism. This means it shouldn't be nearly as hard the landing pad. We will at least try and test this to make sure that it works. I would just focus on making the landing stable and what not.

**Comment by nonagaga** [comment]
I talked to Lester about his requirements for the landing pad. He said to optimize landing area and minimize any wobbling. The old platform is about the right size (3ft x 3ft), but damaged in certain parts and too wobbly to use in competition.
![IMG_4518](https://github.com/user-attachments/assets/2808bc39-c844-49af-94d0-20a4fbdec8f3)

For transport, I'd like the landing pad to be able to be easily removable. That's why I'd like to use a strong, stiff, and light material for the pad. Plywood is light and strong and can be cut to the right size.

![image](https://github.com/user-attachments/assets/cb2e4952-abb7-49fa-9037-f50700ab9b75)

The old mount used 80/20 extrusion to support the weight of the landing pad and drone. This could probably work again, but placing the landing pad closer to the roof of the boat will provide more support points and make it less wobbly.

![image](https://github.com/user-attachments/assets/95cb89ab-ba40-490b-ba1e-d64d0deacc55)

A possible mounting location is outlined above.

**Comment by bcobo04** [comment]
@nonagaga could you send that picture with the red circle again just zoomed out so you can see the rest of the boat?

**Comment by nonagaga** [comment]
![image](https://github.com/user-attachments/assets/9dd44ddb-6791-4e2a-b735-f734127febb7)
Here's the CAD for the landing pad, made out of 4x4 1/4 in plywood. Should be about 10lbs fully assembled. Between career showcase and the storm I didn't get too much done on the CAD, but we should be good to buy 80/20 and the plywood.

**Comment by bcobo04** [comment]
Are we also gonna coat the plywood in smth so it can withstand prolonged sun exposure and water? It would help with longevity so we wouldn’t have to make a new one like every 2 years @nonagaga

**Comment by adamhamdan8** [comment]
Hey @nonagaga could you put the specific stuff you need in the order form? I'm going to buying tons of stuff between now and Thursday. Need to know the specs of everything so that I can get it for you asap

**Comment by adamhamdan8** [comment]
I added @space-cat-explorer as I saw her and @nonagaga putting together the pad yesterday in the lab. If you guys need more help with purchasing. I would recommend finding cheap black grip tape and just spray painting the tape with a bright color, Daniel recommended a bright yellow. Put any of that that you need in the order form!

**Comment by space-cat-explorer** [comment]
Hey! I am going to post some links here for grip tape and paint, but I want to wait for Gabe and Blake to confirm before I put them on the order form: 

Nonslip Grip Tape: 
https://www.lowes.com/pd/ELK-ELK-Anti-Slip-Tape-Heavy-Duty-80-Grit-High-Traction-Nonslip-Griptape-Adhesive-Non-Skid-Treads-for-Steps-Staircases-Hardwood-Flooring-Indoor-and-Outdoor-Use-4-in-x-33-ft-Black/1003238376

Yellow Spray Paint (says it is for exterior/interior and is industrial grade - has good reviews - but I know you guys wanted something specifically latex or polyurethane based)
https://www.amazon.com/Seymour-620-1413-Industrial-Solids-Paint/dp/B0088LV8WM/ref=sr_1_5?dib=eyJ2IjoiMSJ9.3X8shorHPfkyO9_-Aq2sr2PJsvTYUVdmYhEi3qdt4imkGKSTWaxDMPIn2kYYIi8PmnWUH7gFteExg8ZxQ_rMsXkc_XDVzxrIusy0H4kyzD9uFMQmmmhqJuAEpK-XMqadWHD1MH56RQo6Hq-c30TYtXORIfb1TSvm82iHrBVt5e-5p5Df2uxtk2CtmOoGkokHiJzAWqn6QI-JZL7rkT0FsX4wVVaOK-XuvoibwraKrn9DUaEGHCzdxnpbHecIeYdJyxslfbWFBusD5H8HkDNDSK9SQH81mdLcOiA8p08BbXg.r08OTiLUYOpqaaRQfgopRudFM0BhbTiikMnch0Z-rdA&dib_tag=se&hvadid=694313068925&hvdev=c&hvexpln=67&hvlocphy=9193198&hvnetw=g&hvocijid=11710181952638985940--&hvqmt=e&hvrand=11710181952638985940&hvtargid=kwd-1995919395284&hydadcr=15182_13677077&keywords=polyurethane%2Bspray%2Bpaint%2Bwhite&qid=1727981109&sr=8-5&th=1

This one is marine grade - uv resistant and everything we need, but it is clear. So we might need to get another spray paint with color if we want yellow: 
https://www.amazon.com/Polyurethane-Resistant-repairing-protection-sailboat/dp/B09L3NN5VZ/ref=pd_ci_mcx_di_int_sccai_cn_d_sccl_2_3/146-5429588-4402429?pd_rd_w=pEDKB&content-id=amzn1.sym.751acc83-5c05-42d0-a15e-303622651e1e&pf_rd_p=751acc83-5c05-42d0-a15e-303622651e1e&pf_rd_r=PTHCBNEMCH0EPAB6NQ51&pd_rd_wg=emtw4&pd_rd_r=5389e902-f0c2-431a-8e88-d17c4294544f&pd_rd_i=B09L3NN5VZ&psc=1

Same product as the one above, but in white. For some reason the reviews for this one are a little worse: 
https://www.amazon.com/Polyurethane-Resistant-repairing-protection-sailboat/dp/B09L2ZPMYF/ref=sr_1_7?dib=eyJ2IjoiMSJ9.3X8shorHPfkyO9_-Aq2sr2PJsvTYUVdmYhEi3qdt4imkGKSTWaxDMPIn2kYYIi8PmnWUH7gFteExg8ZxQ_rMsXkc_XDVzxrIusy0H4kyzD9uFMQmmmhqJuAEpK-XMqadWHD1MH56RQo6Hq-c30TYtXORIfb1TSvm82iHrBVt5e-5p5Df2uxtk2CtmOoGkokHiJzAWqn6QI-JZL7rkT0FsX4wVVaOK-XuvoibwraKrn9DUaEGHCzdxnpbHecIeYdJyxslfbWFBusD5H8HkDNDSK9SQH81mdLcOiA8p08BbXg.r08OTiLUYOpqaaRQfgopRudFM0BhbTiikMnch0Z-rdA&dib_tag=se&hvadid=694313068925&hvdev=c&hvexpln=67&hvlocphy=9193198&hvnetw=g&hvocijid=11710181952638985940--&hvqmt=e&hvrand=11710181952638985940&hvtargid=kwd-1995919395284&hydadcr=15182_13677077&keywords=polyurethane+spray+paint+white&qid=1727981315&sr=8-7

**Comment by space-cat-explorer** [comment]
For documentation of what we did yesterday: 
- Gabe and I put together the plywood with the corner braces, cut the ends of the screws that were sticking out, and sanded them. 

What still needs to be done (none of these need to be done by Saturday, but should get done asap): 
- Add two small L brackets on the inside of each lip to fully secure all of the boards together 
- Order grip tape and paint
- Add grip tape, paint the structure, and secure it to the boat

**Comment by adamhamdan8** [comment]
Paint is here for the drone landing pad as well as the bolts from McMaster!

**Comment by nonagaga** [comment]
Drone landing pad successfully assembled! All it needs is a paint job. ![image](https://github.com/user-attachments/assets/4019b428-6d55-487b-9e0c-7db5a90743bd)![image](https://github.com/user-attachments/assets/1f3799f8-ee99-4de7-8a9c-2f564e94389d)

**Comment by bcobo04** [comment]
@nonagaga after I left did you end up finishing up the last 2 holes to secure the wood to the aluminum or is it still just bolted through the 2 holes I made in the wood? If so we should drill those final holes before painting.

**Comment by nonagaga** [comment]
Back at home cause of the hurricane, but I'll be drilling the final holes and painting the drone landing pad first thing next week. That should be the last thing required to completely finish the project!

**Comment by bcobo04** [comment]
I will be helping drill the final holes and coat the landing pad with you this Tuesday after the meeting @nonagaga

**Comment by adamhamdan8** [comment]
Lorant hasn't gotten the paint just yet but after you can seal the wood make sure to get the whole thing colored orange!

**Comment by bcobo04** [comment]
@nonagaga and I completed the final structural enhancements of the landing pad and finished the holes used to secure it to the boat this week. These additions make the landing pad fully operational physically for use in testing. We also spray painted about 75% of it before the spray can ran out. We are just waiting on the thicker paint for coating it against the elements and then we will need more orange spray paint if we are to complete its paint job after painting over the progress we previously made.

**Comment by adamhamdan8** [comment]
@bcobo04 and @nonagaga Just wanted to make sure that this is completed before I close the issue

**Comment by bcobo04** [comment]
Yes. @nonagaga and I put finishing touches yesterday by coating it in the new paint making it physically finished. All it needs is the "QR Code" for the drone to see and use to land on the pad, but I was told the coding team would take care of that. Task can be marked complete. @adamhamdan8
