### ISSUE TITLE
Triangulation Software

### ISSUE THREAD

**Issue by nonagaga** [uf-mil-mechanical/tasks#22]
At RobotX, it would be advantageous to our team if we had general estimations on where challenge targets were located in GPS coordinates. Design a system and procedure to triangulate these positions from the shore.

**Comment by nonagaga** [comment]
I finished writing the first version of the triangulation software in Python this week. I'll test it at Wauberg on Sunday. This will help us determine whether phone compasses are precise enough to use for competition.

**Comment by adamhamdan8** [comment]
The triangulation software made by @nonagaga worked very well, and we even made an alternative version for potentially more accurate but more time consuming surveying. @nonagaga if you could share that code here that would be great

**Comment by nonagaga** [comment]
[https://github.com/nonagaga/MIL_Triangulator](url)
Here's a link to a repo containing the Triangulator script I wrote. It requires a google maps API key, which is input as a string literal in the main method. We got the best results by getting exact positions using satellite imagery and measuring the heading from those positions to our unknown.
