### ISSUE TITLE
[Props and Obstacles] Entry Gate

### ISSUE THREAD

**Issue by lorantdomokos** [uf-mil-mechanical/tasks#3]
Associated RobotX task: Entry and Exit Gates

Find/buy/build the buoys, weights and ropes to make the entry gates. See the 2024 RobotX Handbook for more details.

Elements needed:
- [ ] 2 white buoys
- [ ] 1 red buoy
- [ ] 1 green buoy
- [ ] Way to retrieve pinger
- [ ] 1 black buoy

**Comment by adamhamdan8** [comment]
Keep in mind we want one green and one red at least by 8/11/24

**Comment by bcobo04** [comment]
Did we check if we have anything left over in storage that we are building off of or are we building from scratch? @adamhamdan8

**Comment by bcobo04** [comment]
![image_2024-09-04_135935306](https://github.com/user-attachments/assets/294ecd9c-c703-4cc1-bf95-3965d015d489)
This are the specs from their website

**Comment by adamhamdan8** [comment]
Hey @DiegoDom23 I assigned you to this task for this week. It seems that we only need one black buoy so we can just stick with the buoy that we have for now. I may have misremembered but I believe that means you just need to cut the corrugated plastic and paint it black. Let me know if you need anything else for this!

**Comment by adamhamdan8** [comment]
@DiegoDom23 Going to message you on discord soon, but will you be able to come in and get that last buoy done before Sunday?

**Comment by DiegoDom23** [comment]
Black buoy is done and ready for testing on Sunday
![black_buoy](https://github.com/user-attachments/assets/d741952b-bd26-410c-9fd5-c1874358540a)

**Comment by adamhamdan8** [comment]
Thank you for getting that done! Last thing we need to do is test the pinger, and we already have it assembled and everything we just need to tie a weight to it, maybe also a little buoy so we can easily find it!
