### ISSUE TITLE
[Props and Obstacles] Dock & Deliver

### ISSUE THREAD

**Issue by amcaleer271** [uf-mil-mechanical/tasks#9]
We need to simulate the docking area as well as the target for the ball launcher in the following setup. 
<img width="751" alt="Screen Shot 2024-09-24 at 1 41 05 PM" src="https://github.com/user-attachments/assets/f8c074ca-aece-4012-b4f9-1afa01f60502">

PVC structure is probably the easiest way to do this, just a single docking area with a spot for the target would be good. There is a chance that this won't be tested, but the plans should be made anyways. Make the target out of laminated paper that is mounted to another frame!

**Comment by adamhamdan8** [comment]
@DiegoDom23 @csachs32 Just updated the description, but obviously check the handbook too!

**Comment by DiegoDom23** [comment]
We are going to work on one of the 180in x 180in (15 ft x 15 ft) square docks with the deliver panel as shown in the image
![image](https://github.com/user-attachments/assets/5f6d3ce1-0a28-4908-815a-da70cd1f79ea)

**Comment by DiegoDom23** [comment]
The deliver task panel we made to be printed is attached, dimensions should be printed at 92.5 inches for heigh and 48 inches for width
![Deliver_Task_panel](https://github.com/user-attachments/assets/f40596f0-edb8-4d2f-993a-effdd08cc9bd)

**Comment by DiegoDom23** [comment]
We will need 5 feet pvc pipe 1 inch diameter x9, pvc pipe coupling for 1 inch diameter x6, pvc corner piece for 1 inch diameter x2

**Comment by adamhamdan8** [comment]
> We will need 5 feet pvc pipe 1 inch diameter x9, pvc pipe coupling for 1 inch diameter x6, pvc corner piece for 1 inch diameter x2

I got some of the 1 inch pipe, but they were out and told me "TBD" for the replenishment date. Annoying but we will have to check another Lowe's sometime soon.

**Comment by adamhamdan8** [comment]
Okay hurricane really throws a wrench in this one, but when we get back I will hopefully have PVC and laminated print ready for you guys!

**Comment by DiegoDom23** [comment]
Hurricane messed up planning, but with materials ready, I will be able to finish this by the end of the week to have it ready for Sunday.

**Comment by csachs32** [comment]
I will also be helping Diego build these once materials are available.

**Comment by adamhamdan8** [comment]
I think since we have two testing sessions left I will have to discuss with software to see if they are even ready to test this. I will let you guys know tomorrow if we are continuing with this.

**Comment by adamhamdan8** [comment]
@DiegoDom23 @csachs32 Lorant was not able to go to Lowe's last night, and so unless you guys are able to come in Friday and Saturday to put everything together then we might have to scratch the building of these task elements

**Comment by DiegoDom23** [comment]
I am able to come in tomorrow after like 1:30 but I thought there was going to be no power in Malanchowsky. If we can still access the building I'll go to work on it

**Comment by DiegoDom23** [comment]
Materials weren't able to be bought on time but now that they are in the lab, it should be done by Wednesday.

**Comment by csachs32** [comment]
PVC stand has been built, waiting on the target itself to attach. Will simply tie it to the PVC using zip ties.

**Comment by adamhamdan8** [comment]
Wrote this in discord, but we have a tarp and black paint and tape and what not so that you guys can make the tarp in the lab. Printing would be annoying and difficult.

**Comment by csachs32** [comment]
Made the target! It is in the lab next to the Kobalt tool box. Last thing that is needed is to zip tie the target to the PVC frame by cutting small holes in the sides of the target. For transportation, it would be easiest to attach the target to the frame at the lake.

**Comment by DiegoDom23** [comment]
Grabbed the completed tarp today from solar park and brought it to lake wauburg to be used for testing today. Unfortunately, the stand was left behind in CIMAR and we could not get in without access. Had to leave testing early to complete assignments for class, but the task should be completed as it is ready to be used in any future testing.

**Comment by adamhamdan8** [comment]
Great I am going to close this issue, it seems like we have it under wraps!
